### ISSUE TITLE
World generation exception

### ISSUE THREAD

**Issue by 19300000** [FatherToast/DeadlyWorld#1]
The bystander model sees a lot of irregular water and magma

**Comment by FatherToast** [comment]
What is the issue, exactly?

**Comment by 19300000** [comment]
> What is the issue, exactly?

[https://www.mcmod.cn/class/4491.html](url)
You can see the details of the picture on the 9th floor. i can't send pictures here

**Comment by 19300000** [comment]
> What is the issue, exactly?
You'll understand when you see it

**Comment by 19300000** [comment]
> What is the issue, exactly?

You'll understand when you see it

**Comment by FatherToast** [comment]
Working as intended - these are called water veins and lava veins and can be configured/disabled in the config.
